name: Deploy Mernstack Perfume App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  client:
    name: Deploy Client to Netlify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies (Client)
        run: npm install
        working-directory: ./client

      - name: Build Client
        run: npm run build
        working-directory: ./client
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}

      - name: Deploy to Netlify (Client)
        uses: nwtgck/actions-netlify@v2
        with:
          publish-dir: ./client/dist
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy Client from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: false
          enable-commit-status: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }} #nfp_k1c35LBNHMz9uSvC78Fxsjm6VEDGfhAbcc32
          NETLIFY_SITE_ID: ${{ secrets.CLIENT_SITE_ID }}

  admin:
    name: Deploy Admin to Netlify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies (Admin)
        run: npm install --legacy-peer-deps
        working-directory: ./admin

      - name: Build Admin
        run: npm run build
        working-directory: ./admin
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}

      - name: Deploy to Netlify (Admin)
        uses: nwtgck/actions-netlify@v2
        with:
          publish-dir: ./admin/dist
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy Admin from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: false
          enable-commit-status: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.ADMIN_SITE_ID }}

  backend:
    name: Deploy Backend to Render
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          serviceId: ${{ secrets.RENDER_SERVICE_ID }}
          apiKey: ${{ secrets.RENDER_API_KEY }}  #rnd_mt8KzZSXMxOyIHWBhMPxdBEaMdM6